on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run the build action
        uses: kevincorizi/me/.github/build@master
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DOMAIN: ${{ secrets.FTP_DOMAIN }}
          LOCAL_FOLDER: ${{ secrets.LOCAL_FOLDER }}
          REMOTE_FOLDER: ${{ secrets.REMOTE_FOLDER }}